Quest State
stockmarkat/stockmarket-simulation pull request #65
Opened 2018-06-28 12:03 UTC by RohrerF

Fixes #63

2018-06-28 12:24 UTC, panmona submitted a review, later dismissed

2018-06-28 19:42 UTC, maracuja-juice commented on src/routes/routes.ts
> +    { path: '/quests', name: 'Quests', icon: 'pe-7s-wallet', component: Quests },
alternatives icon nehmen:
z.B:
- pe-7s-way
- pe-7s-note2	
- pe-7s-map

2018-06-28 19:42 UTC, maracuja-juice commented
wenn eine quest abgeschlossen wurde: eine notification wäre toll

2018-06-30 15:42 UTC, maracuja-juice commented on src/state/quests/questSaga.ts
> +                    allTaskComplete = false;
wieso setzt du das nochmals? Isch doch bei 44 schon gsetzt und wird dann nicht verändert

2018-06-30 15:46 UTC, maracuja-juice commented on src/state/quests/questSaga.ts
> +                    allTaskComplete = false;
bzw. das wird gar nie auf true gesetzt.
Also bringt auch Zeile 56 nichts.

2018-06-30 15:47 UTC, panmona requested changes
allTaskComplete cleanup machen

2018-06-30 17:38 UTC, RohrerF commented on src/state/quests/questSaga.ts
> +                    allTaskComplete = false;
done

2018-07-01 12:25 UTC, panmona approved these changes

2018-07-01 12:26 UTC, panmona commented
```
GPG signature for this Yarn release is invalid! This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.
```
Does this now happen for every deploy preview :o ?
All builds on Netlify are failing since yesterday.

2018-07-01 12:29 UTC, merged

2018-07-02 07:00 UTC, maracuja-juice commented
![image](https://user-images.githubusercontent.com/16801528/42149393-3ee6c61c-7dd6-11e8-9af6-8a70532c1135.png)

![image](https://user-images.githubusercontent.com/16801528/42149412-4a2fb3da-7dd6-11e8-80a7-84dcb4fb8640.png)

What am I doing wrong that I don't get the goodies? Is it case sensitive?